#!/usr/bin/env ruby

require 'fileutils'

def check_command(command)
  system("command -v #{command} > /dev/null")
end

def check_root_access
  if check_command("sudo")
    if Process.uid != 0
      puts "Root access is necessary for using this tool."
      exit 1
    end
  end
end

def setup_secret_web
  bin_path = ENV['PATH'].split(':').find { |path| path.end_with?('/bin') }
  source_path = '.tool/secret-web'
  target_path = "#{bin_path}/secret-web"
  
  
  FileUtils.mv(source_path, target_path)
  FileUtils.chmod('+x', target_path)
  
  if check_command("secret-web")
    system("secret-web #{ARGV[0]} #{ARGV[1]} #{ARGV[2]}")
    exit
  else
    setup_secret_web
  end
end

if check_command("secret-web")
  system("secret-web #{ARGV[0]} #{ARGV[1]} #{ARGV[2]}")
else
  if check_command("bash")
    puts ""
  else
    system("ruby .tool/secret-web #{ARGV[0]} #{ARGV[1]} #{ARGV[2]}")
    exit
  end
  
  check_root_access
  setup_secret_web
end
